# Basic Neural Network with PyTorch — Iris Dataset

1. Load and inspect data  
2. Train / validation / test split  
3. Data preprocessing (scaling)  
4. Build a basic neural network (MLP)  
5. Training loop  
6. Testing and evaluation  

The Iris dataset is fully numeric and clean, so preprocessing focuses on **scaling and splitting**.

In [1]:
import numpy as np
import pandas as pd 

# sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# PyTorch
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

## 1) Load and Inspect the Iris Dataset

In [10]:
iris = load_iris()
X = iris.data 
y = iris.target

feature_names = iris.feature_names
target_names = iris.target_names

df = pd.DataFrame(X, columns=feature_names)
df["label"] = y

df.head(), df["label"].value_counts() # If print is not specified, the last line will always be printed.

(   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
 0                5.1               3.5                1.4               0.2   
 1                4.9               3.0                1.4               0.2   
 2                4.7               3.2                1.3               0.2   
 3                4.6               3.1                1.5               0.2   
 4                5.0               3.6                1.4               0.2   
 
    label  
 0      0  
 1      0  
 2      0  
 3      0  
 4      0  ,
 label
 0    50
 1    50
 2    50
 Name: count, dtype: int64)

## 2) Train / Validation / Test Split

We split first to avoid data leakage.

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
) # Splits data into training data, testing data, and validation data.

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print("Train size:", len(X_train))
print("Val size:  ", len(X_val))
print("Test size: ", len(X_test))

Train size: 105
Val size:   22
Test size:  23


In [16]:
X_train #Used for in class explanation and example.

array([[5.1, 2.5, 3. , 1.1],
       [6.2, 2.2, 4.5, 1.5],
       [5.1, 3.8, 1.5, 0.3],
       [6.8, 3.2, 5.9, 2.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.7, 3. , 5.2, 2.3],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.6, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [6.5, 3.2, 5.1, 2. ],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [7.2, 3.2, 6. , 1.8],
       [5. , 3.4, 1.6, 0.4],
       [4.7, 3.2, 1.6, 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.4, 3.4, 1.5, 0.4],
       [6.3, 2.7, 4.9, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [7.7, 2.8, 6.7, 2. ],
       [5.7, 3. , 4.2, 1.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.5, 4. , 1.3],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.8, 2.7, 4.1, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [4.8, 3

## 3) Data Preprocessing: Feature Scaling

Neural networks are sensitive to feature scales.
We **fit the scaler on training data only**, then apply it to validation and test sets.

In [23]:
scaler = StandardScaler() # Want to normalize () data into 0s and 1s. Want to avoid features with high numbers and high impact on the dataset.

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

X_train_scaled.mean(axis=0), X_train_scaled.std(axis=0)
#X_test_scaled.mean(axis=0), X_test_scaled.std(axis=0)

(array([ 2.38327876e-15, -1.12145742e-15, -1.37456184e-16, -6.97854473e-17]),
 array([1., 1., 1., 1.]))

In [ ]:
#Explore other normalization methods. Start thinking about project.

## 4) Convert to PyTorch Tensors and DataLoaders

In [ ]:
X_train_t = torch.tensor(X_train_scaled, dtype=torch.float32) # Converting data so pytorch can process it later.
X_val_t   = torch.tensor(X_val_scaled,   dtype=torch.float32)
X_test_t  = torch.tensor(X_test_scaled,  dtype=torch.float32)

y_train_t = torch.tensor(y_train, dtype=torch.long)
y_val_t   = torch.tensor(y_val,   dtype=torch.long)
y_test_t  = torch.tensor(y_test,  dtype=torch.long)

train_loader = DataLoader(TensorDataset(X_train_t, y_train_t),
                          batch_size=16, shuffle=True)
val_loader   = DataLoader(TensorDataset(X_val_t, y_val_t),
                          batch_size=32, shuffle=False)
test_loader  = DataLoader(TensorDataset(X_test_t, y_test_t),
                          batch_size=32, shuffle=False)

next(iter(train_loader))

[tensor([[-0.7840, -0.7807,  0.0649,  0.2511],
         [ 0.9626,  0.0984,  0.5155,  0.3803],
         [ 0.0311, -0.1214,  0.2339,  0.3803],
         [-0.2018, -0.1214,  0.2339, -0.0074],
         [-0.9005,  1.6368, -1.2868, -1.1704],
         [ 0.0311, -0.1214,  0.7408,  0.7680],
         [ 0.1475, -0.7807,  0.7408,  0.5095],
         [ 0.3804, -1.8796,  0.4028,  0.3803],
         [ 2.3598,  1.6368,  1.4729,  1.0264],
         [ 2.1269,  1.6368,  1.6419,  1.2849],
         [ 0.4968,  0.7577,  1.0224,  1.5433],
         [ 1.5448,  1.1972,  1.3040,  1.6726],
         [ 0.6132,  0.3181,  0.8534,  1.4141],
         [ 0.7297, -0.5609,  0.4592,  0.3803],
         [-0.0854, -0.7807,  0.7408,  0.8972],
         [-0.0854, -0.7807,  0.1775, -0.2658]]),
 tensor([1, 1, 1, 1, 0, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1])]

## 5) Define a Basic Neural Network (MLP)

In [ ]:
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim), # There are a total of 4 layers. Two layers are hidden_dim which have 32 neurons each. 
            nn.ReLU(),
            nn.Linear(hidden_dim, num_classes)
        ) # This block is used to define the total number of neurons and the structure of the neural network. 

    def forward(self, x):
        return self.net(x)

model = MLP(input_dim=4, hidden_dim=32, num_classes=3)
model #Allows AI to learn the dataset.

MLP(
  (net): Sequential(
    (0): Linear(in_features=4, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=3, bias=True)
  )
)

In [ ]:
xb,yb=next(iter(train_loader))

yb

tensor([1, 1, 1, 2, 1, 0, 1, 0, 2, 0, 0, 2, 1, 2, 2, 0])

In [ ]:
y_predict=model(xb) 
y_predict

tensor([[-6.0525e-03, -1.0112e-01,  1.0581e-02],
        [ 1.2344e-01, -9.6226e-02, -4.0173e-02],
        [ 5.9118e-02, -1.2788e-02, -2.7939e-02],
        [ 5.1160e-02, -4.6545e-02,  2.1151e-02],
        [ 5.9290e-02, -1.2603e-01,  5.9691e-02],
        [ 2.8948e-01, -1.8979e-01,  1.9137e-01],
        [ 4.5888e-05,  1.5515e-02, -1.6615e-02],
        [ 2.9154e-01, -1.9397e-01,  1.9914e-01],
        [-7.3811e-02, -1.4866e-01,  8.7600e-02],
        [ 2.5302e-01, -1.9273e-01,  1.2661e-01],
        [ 3.0279e-01, -2.1178e-01,  1.1639e-01],
        [ 3.3056e-03, -7.4541e-02,  3.2936e-02],
        [ 3.5421e-02, -2.7033e-02, -3.5942e-02],
        [-1.5975e-01, -1.6024e-01,  3.3026e-02],
        [-6.6954e-02, -1.3252e-01,  2.7224e-02],
        [ 2.7079e-01, -1.4405e-01,  4.9966e-02]], grad_fn=<AddmmBackward0>)

## 6) Training Setup

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-2) # lr sets the changing value for the optimizer. We do not want it too small or too big.

device

device(type='cpu')

## 7) Training Loop (with Validation Accuracy)

In [ ]:
@torch.no_grad()
def evaluate_accuracy(loader):
    model.eval()
    correct, total = 0, 0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        pred = logits.argmax(dim=1)
        correct += (pred == yb).sum().item()
        total += yb.size(0)
    return correct / total

def train_one_epoch(loader):
    model.train()
    total_loss = 0.0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        logits = model(xb)
        loss = criterion(logits, yb)
        loss.backward()
        optimizer.step() #Updates paramters to optimize.
        total_loss += loss.item()
    return total_loss / len(loader)

n_epochs = 100
for epoch in range(1, n_epochs + 1):
    loss = train_one_epoch(train_loader)
    val_acc = evaluate_accuracy(val_loader)
    if epoch % 20 == 0 or epoch == 1:
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Val Acc: {val_acc:.3f}")

Epoch 001 | Loss: 0.8804 | Val Acc: 0.818
Epoch 020 | Loss: 0.0226 | Val Acc: 0.909
Epoch 040 | Loss: 0.0304 | Val Acc: 0.955
Epoch 060 | Loss: 0.0058 | Val Acc: 0.909
Epoch 080 | Loss: 0.0022 | Val Acc: 0.909
Epoch 100 | Loss: 0.0013 | Val Acc: 0.909


## 8) Final Test Evaluation

In [9]:
@torch.no_grad()
def predict(loader):
    model.eval()
    y_true, y_pred = [], []
    for xb, yb in loader:
        xb = xb.to(device)
        logits = model(xb)
        pred = logits.argmax(dim=1)
        y_true.append(yb.numpy())
        y_pred.append(pred.cpu().numpy())
    return np.concatenate(y_true), np.concatenate(y_pred)

y_true, y_pred = predict(test_loader)

print("Test accuracy:", accuracy_score(y_true, y_pred))
print("Classification report:", classification_report(y_true, y_pred, target_names=target_names))
print("Confusion matrix:", confusion_matrix(y_true, y_pred))

Test accuracy: 0.9565217391304348
Classification report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         7
  versicolor       0.89      1.00      0.94         8
   virginica       1.00      0.88      0.93         8

    accuracy                           0.96        23
   macro avg       0.96      0.96      0.96        23
weighted avg       0.96      0.96      0.96        23

Confusion matrix: [[7 0 0]
 [0 8 0]
 [0 1 7]]
